import { coinflip } from "./commands/Coinflip"
import { enderPearlCommand } from "./commands/EnderPearlCommand"
import { inflatableJerriesCommand } from "./commands/InflatableJerriesCommand"
import { refillCommand } from "./commands/RefillCommand"
import { rotate } from "./commands/Rotate"
import { sound } from "./commands/SoundCommand"
import { valleyCommand } from "./commands/ValleyCommand"

import { mpCommand, pbCommand, lvlCommand } from "./features/CheckStats"

import "./features/AtLocationMessages"
import "./features/AutoKickValley"
import "./features/AutoOpenPotionBag"
import "./features/AutoRefill"
import "./features/BloodCampHelper"
import "./features/BloodRushSplits"
import "./features/CompactHoppityMessages"
import "./features/CooldownKickMessage"
import "./features/CrystalPlaceTimer"
import "./features/CrystalSpawnTimer"
import "./features/DragonSpawnTimer"
import "./features/DungeonWarpCooldown"
import "./features/DupeClassChecker"
import "./features/ExplosiveShot"
import "./features/GoldorTickTimer"
import "./features/HidePlayersAfterLeap"
import "./features/InvincibilityMessages"
import "./features/ItemHighlight"
import "./features/KuudraDPS"
import "./features/LimboCommand"
import "./features/P3StartTimer"
import "./features/PadTickTimer"
import "./features/PictureOnScreen"
import "./features/PredevTimer"
import "./features/Pre4Notifier"
import "./features/ReaperDisplay"
import "./features/RelicSpawnTimer"
import "./features/RelicTimer"
import "./features/RelicUtils"
import "./features/Reminder"
import "./features/RunSplits"
import "./features/ScoreMilestones"
import "./features/StonkSwap"
import "./features/Stopwatch"
import "./features/TerminalTimestamps"

import "./util/FirstInstall"